### ISSUE TITLE
Salt Websocket thread crashes, resulting in out-of-sync data

### ISSUE THREAD

**Issue by SGA-max-faxalv** [resalt-dev/resalt#20]
salt_resalt.1.6ei2wxto3i6w@eulunlnxp018v    | [2022-11-25T11:22:49Z DEBUG resalt::salt::listener] salt event job fun: "state.apply"                                                                                                   salt_resalt.1.6ei2wxto3i6w@eulunlnxp018v    | thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', src/salt/listener.rs:182:46
salt_resalt.1.6ei2wxto3i6w@eulunlnxp018v    | note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by SGA-max-faxalv** [comment]
https://github.com/resalt-dev/resalt/blob/main/src/salt/listener.rs#L181

Invalid assumption, "test" can not only be string, but also boolean, e.g. `{ "test": true" }`

**Comment by Foorack** [comment]
Fixed in https://github.com/resalt-dev/resalt/commit/06e9eac8d28a0a69fe13b476ae5b1e384332a098
